"""add_csv_upload_tables

Revision ID: 9421f245f151
Revises: f236931b404d
Create Date: 2026-02-25 16:37:42.299458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9421f245f151'
down_revision: Union[str, Sequence[str], None] = 'f236931b404d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csv_mapping_profile',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('column_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mapping', sa.JSON(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_csv_mapping_profile_column_hash'), 'csv_mapping_profile', ['column_hash'], unique=False)
    op.create_index(op.f('ix_csv_mapping_profile_created_at'), 'csv_mapping_profile', ['created_at'], unique=False)
    op.create_index(op.f('ix_csv_mapping_profile_user_id'), 'csv_mapping_profile', ['user_id'], unique=False)
    op.create_table('csv_upload_session',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mapping_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('proposed_mapping', sa.JSON(), nullable=False),
    sa.Column('csv_content', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_csv_upload_session_created_at'), 'csv_upload_session', ['created_at'], unique=False)
    op.create_index(op.f('ix_csv_upload_session_mapping_id'), 'csv_upload_session', ['mapping_id'], unique=True)
    op.create_index(op.f('ix_csv_upload_session_user_id'), 'csv_upload_session', ['user_id'], unique=False)
    op.add_column('transaction', sa.Column('fingerprint', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_transaction_fingerprint'), 'transaction', ['fingerprint'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_fingerprint'), table_name='transaction')
    op.drop_column('transaction', 'fingerprint')
    op.drop_index(op.f('ix_csv_upload_session_user_id'), table_name='csv_upload_session')
    op.drop_index(op.f('ix_csv_upload_session_mapping_id'), table_name='csv_upload_session')
    op.drop_index(op.f('ix_csv_upload_session_created_at'), table_name='csv_upload_session')
    op.drop_table('csv_upload_session')
    op.drop_index(op.f('ix_csv_mapping_profile_user_id'), table_name='csv_mapping_profile')
    op.drop_index(op.f('ix_csv_mapping_profile_created_at'), table_name='csv_mapping_profile')
    op.drop_index(op.f('ix_csv_mapping_profile_column_hash'), table_name='csv_mapping_profile')
    op.drop_table('csv_mapping_profile')
    # ### end Alembic commands ###
